import {createStore} from 'satcheljs';
import ExampleStore from './ExampleStore';

export default createStore<ExampleStore>('ExampleStore', {
    items: [
        // tslint:disable:quotemark
        {"name":"Red-capped cardinal","description":"Paroaria gularis"},
        {"name":"Woylie","description":"Bettongia penicillata"},
        {"name":"Wallaby, agile","description":"Macropus agilis"},
        {"name":"Egyptian goose","description":"Alopochen aegyptiacus"},
        {"name":"Common genet","description":"Genetta genetta"},
        {"name":"Cormorant, king","description":"Phalacrocorax albiventer"},
        {"name":"Southern tamandua","description":"Tamandua tetradactyla"},
        {"name":"Openbill, asian","description":"Anastomus oscitans"},
        {"name":"Whale, baleen","description":"Eubalaena australis"},
        {"name":"Crane, wattled","description":"Bugeranus caruncalatus"},
        {"name":"Koala","description":"Phascolarctos cinereus"},
        {"name":"Ocelot","description":"Felis pardalis"},
        {"name":"Porcupine, african","description":"Hystrix cristata"},
        {"name":"Shrike, common boubou","description":"Laniarius ferrugineus"},
        {"name":"Ibis, puna","description":"Plegadis ridgwayi"},
        {"name":"Tree porcupine","description":"Coendou prehensilis"},
        {"name":"Bustard, stanley","description":"Neotis denhami"},
        {"name":"Baboon, olive","description":"Papio cynocephalus"},
        {"name":"Kingfisher, white-throated","description":"Halcyon smyrnesis"},
        {"name":"White spoonbill","description":"Platalea leucordia"},
        {"name":"Pintail, white-cheeked","description":"Anas bahamensis"},
        {"name":"Fisher","description":"Martes pennanti"},
        {"name":"Black-eyed bulbul","description":"Pycnonotus barbatus"},
        {"name":"Screamer, crested","description":"Chauna torquata"},
        {"name":"Kangaroo, jungle","description":"Macropus agilis"},
        {"name":"Waxbill, violet-eared","description":"Uraeginthus granatina"},
        {"name":"Northern phalarope","description":"Phalaropus lobatus"},
        {"name":"Openbill, asian","description":"Anastomus oscitans"},
        {"name":"Egret, cattle","description":"Bubulcus ibis"},
        {"name":"Caribou","description":"Rangifer tarandus"},
        {"name":"Western patch-nosed snake","description":"Salvadora hexalepis"},
        {"name":"Possum, pygmy","description":"Acrobates pygmaeus"},
        {"name":"Boa, malagasy ground","description":"Acrantophis madagascariensis"},
        {"name":"Puna ibis","description":"Plegadis ridgwayi"},
        {"name":"Waterbuck, common","description":"Kobus defassa"},
        {"name":"Hornbill, southern ground","description":"Bucorvus leadbeateri"},
        {"name":"Whale, baleen","description":"Eubalaena australis"},
        {"name":"Hedgehog, south african","description":"Erinaceus frontalis"},
        {"name":"Pelican, brown","description":"Pelecanus occidentalis"},
        {"name":"Screamer, southern","description":"Chauna torquata"},
        {"name":"Goose, cape barren","description":"Cereopsis novaehollandiae"},
        {"name":"Waved albatross","description":"Diomedea irrorata"},
        {"name":"Oryx, beisa","description":"Oryx gazella"},
        {"name":"White-necked raven","description":"Corvus albicollis"},
        {"name":"Little cormorant","description":"Phalacrocorax niger"},
        {"name":"Blackish oystercatcher","description":"Haematopus ater"},
        {"name":"Boa, cook's tree","description":"Corallus hortulanus cooki"},
        {"name":"Common genet","description":"Genetta genetta"},
        {"name":"Trumpeter, green-winged","description":"Psophia viridis"},
        {"name":"Rattlesnake, horned","description":"Crotalus cerastes"},
        {"name":"Wildebeest, blue","description":"Connochaetus taurinus"},
        {"name":"African fish eagle","description":"Haliaetus vocifer"},
        {"name":"Short-nosed bandicoot","description":"Isoodon obesulus"},
        {"name":"Giant armadillo","description":"Priodontes maximus"},
        {"name":"Australian spiny anteater","description":"Tachyglossus aculeatus"},
        {"name":"Mongoose, javan gold-spotted","description":"Herpestes javanicus"},
        {"name":"Southern tamandua","description":"Tamandua tetradactyla"},
        {"name":"Mexican wolf","description":"Canis lupus baileyi"},
        {"name":"Bush dog","description":"Speothos vanaticus"},
        {"name":"Turkey, australian brush","description":"Alectura lathami"},
        {"name":"Large cormorant","description":"Phalacrocorax carbo"},
        {"name":"Macaw, blue and gold","description":"Ara ararauna"},
        {"name":"Common langur","description":"Semnopithecus entellus"},
        {"name":"Monkey, red howler","description":"Alouatta seniculus"},
        {"name":"Red hartebeest","description":"Alcelaphus buselaphus caama"},
        {"name":"Snake, eastern indigo","description":"Drymarchon corias couperi"},
        {"name":"Ground monitor (unidentified)","description":"Varanus sp."},
        {"name":"Black-fronted bulbul","description":"Pycnonotus nigricans"},
        {"name":"Lark, horned","description":"Eremophila alpestris"},
        {"name":"Adouri (unidentified)","description":"unavailable"},
        {"name":"Common dolphin","description":"Delphinus delphis"},
        {"name":"Spoonbill, white","description":"Platalea leucordia"},
        {"name":"Red-billed buffalo weaver","description":"Bubalornis niger"},
        {"name":"Caracal","description":"Felis caracal"},
        {"name":"Long-finned pilot whale","description":"Globicephala melas"},
        {"name":"Black-capped chickadee","description":"Parus atricapillus"},
        {"name":"Armadillo, nine-banded","description":"Dasypus novemcinctus"},
        {"name":"Monkey, bleeding heart","description":"Theropithecus gelada"},
        {"name":"Indian giant squirrel","description":"Ratufa indica"},
        {"name":"Chestnut weaver","description":"Ploceus rubiginosus"},
        {"name":"Nilgai","description":"Boselaphus tragocamelus"},
        {"name":"Crane, black-crowned","description":"Balearica pavonina"},
        {"name":"Wallaby, red-necked","description":"Macropus rufogriseus"},
        {"name":"Otter, canadian river","description":"Lutra canadensis"},
        {"name":"Yellow-brown sungazer","description":"Cordylus giganteus"},
        {"name":"Armadillo, nine-banded","description":"Dasypus novemcinctus"},
        {"name":"Blue wildebeest","description":"Connochaetus taurinus"},
        {"name":"White-browed sparrow weaver","description":"Plocepasser mahali"},
        {"name":"Waxbill, violet-eared","description":"Uraeginthus granatina"},
        {"name":"Brown and yellow marshbird","description":"Pseudoleistes virescens"},
        {"name":"Porcupine, african","description":"Hystrix cristata"},
        {"name":"Sun gazer","description":"Cordylus giganteus"},
        {"name":"Gerenuk","description":"Litrocranius walleri"},
        {"name":"European badger","description":"Meles meles"},
        {"name":"Pintail, white-cheeked","description":"Anas bahamensis"},
        {"name":"Fox, blue","description":"Alopex lagopus"},
        {"name":"Cardinal, black-throated","description":"Paroaria gularis"},
        {"name":"Dog, african wild","description":"Lycaon pictus"},
        {"name":"Vulture, white-headed","description":"Aegypius occipitalis"},
        {"name":"Spoonbill, european","description":"Platalea leucordia"},
        {"name":"Arctic lemming","description":"Dicrostonyx groenlandicus"},
        {"name":"Cormorant (unidentified)","description":"unavailable"},
        {"name":"Steenbok","description":"Raphicerus campestris"},
        {"name":"Galapagos hawk","description":"Buteo galapagoensis"},
        {"name":"White rhinoceros","description":"Ceratotherium simum"},
        {"name":"Yellow-billed hornbill","description":"Tockus flavirostris"},
        {"name":"Jackrabbit, white-tailed","description":"Lepus townsendii"},
        {"name":"Dama wallaby","description":"Macropus eugenii"},
        {"name":"Fox, cape","description":"Vulpes chama"},
        {"name":"Darter, african","description":"Anhinga rufa"},
        {"name":"Elephant, asian","description":"Elephas maximus bengalensis"},
        {"name":"Carmine bee-eater","description":"Merops nubicus"},
        {"name":"White-fronted capuchin","description":"Cebus albifrons"},
        {"name":"Common brushtail possum","description":"Trichosurus vulpecula"},
        {"name":"Glossy ibis","description":"Plegadis falcinellus"},
        {"name":"Stick insect","description":"Leprocaulinus vipera"},
        {"name":"Colobus, magistrate black","description":"Colobus guerza"},
        {"name":"Deer, white-tailed","description":"Odocoilenaus virginianus"},
        {"name":"Possum, golden brush-tailed","description":"Trichosurus vulpecula"},
        {"name":"African porcupine","description":"Hystrix cristata"},
        {"name":"Peccary, white-lipped","description":"Tayassu pecari"},
        {"name":"Wattled crane","description":"Bugeranus caruncalatus"},
        {"name":"Oribi","description":"Ourebia ourebi"},
        {"name":"Viper, egyptian","description":"Naja haje"},
        {"name":"Sloth bear","description":"Melursus ursinus"},
        {"name":"Fox, silver-backed","description":"Vulpes chama"},
        {"name":"Colobus, white-mantled","description":"Colobus guerza"},
        {"name":"Sloth, hoffman's","description":"Choloepus hoffmani"},
        {"name":"Kangaroo, red","description":"Macropus rufus"},
        {"name":"Lemur, grey mouse","description":"Microcebus murinus"},
        {"name":"Boa, malagasy ground","description":"Acrantophis madagascariensis"},
        {"name":"Armadillo, giant","description":"Priodontes maximus"},
        {"name":"Euro wallaby","description":"Macropus robustus"},
        {"name":"Brolga crane","description":"Grus rubicundus"},
        {"name":"Egyptian goose","description":"Alopochen aegyptiacus"},
        {"name":"Collared lizard","description":"Crotaphytus collaris"},
        {"name":"Manatee","description":"Trichechus inunguis"},
        {"name":"Shrike, crimson-breasted","description":"Laniaurius atrococcineus"},
        {"name":"Crowned hawk-eagle","description":"Spizaetus coronatus"},
        {"name":"Coyote","description":"Canis latrans"},
        {"name":"Crane, sandhill","description":"Grus canadensis"},
        {"name":"Langur, gray","description":"Semnopithecus entellus"},
        {"name":"Canadian river otter","description":"Lutra canadensis"},
        {"name":"Polar bear","description":"Ursus maritimus"},
        {"name":"Greylag goose","description":"Anser anser"},
        {"name":"European shelduck","description":"Tadorna tadorna"},
        {"name":"Vulture, king","description":"Sarcorhamphus papa"},
        {"name":"Eurasian red squirrel","description":"Sciurus vulgaris"},
        {"name":"Dusky gull","description":"Larus fuliginosus"},
        {"name":"Goose, egyptian","description":"Alopochen aegyptiacus"},
        {"name":"Armadillo, giant","description":"Priodontes maximus"},
        {"name":"Secretary bird","description":"Sagittarius serpentarius"},
        {"name":"Owl, white-browed","description":"Ninox superciliaris"},
        {"name":"Pale-throated three-toed sloth","description":"Bradypus tridactylus"},
        {"name":"Black-backed magpie","description":"Gymnorhina tibicen"},
        {"name":"Screamer, crested","description":"Chauna torquata"},
        {"name":"Parakeet, rose-ringed","description":"Psittacula krameri"},
        {"name":"Savanna baboon","description":"Papio cynocephalus"},
        {"name":"Squirrel, grey-footed","description":"Paraxerus cepapi"},
        {"name":"Weaver, lesser masked","description":"Ploceus intermedius"},
        {"name":"Shrew, mandras tree","description":"Anathana ellioti"},
        {"name":"Madagascar fruit bat","description":"Pteropus rufus"},
        {"name":"Baboon, chacma","description":"Papio ursinus"},
        {"name":"Dromedary camel","description":"Camelus dromedarius"},
        {"name":"Oriental short-clawed otter","description":"Aonyx cinerea"},
        {"name":"Ibex","description":"Capra ibex"},
        {"name":"Monkey, black spider","description":"Ateles paniscus"},
        {"name":"Egyptian goose","description":"Alopochen aegyptiacus"},
        {"name":"White-winged tern","description":"Chlidonias leucopterus"},
        {"name":"Eastern quoll","description":"Dasyurus viverrinus"},
        {"name":"Teal, hottentot","description":"Anas punctata"},
        {"name":"Black-eyed bulbul","description":"Pycnonotus barbatus"},
        {"name":"Green vine snake","description":"Oxybelis fulgidus"},
        {"name":"Magpie, australian","description":"Gymnorhina tibicen"},
        {"name":"Common eland","description":"Taurotagus oryx"},
        {"name":"Grenadier, purple","description":"Uraeginthus granatina"},
        {"name":"Red-winged blackbird","description":"Agelaius phoeniceus"},
        {"name":"Striped hyena","description":"Hyaena hyaena"},
        {"name":"Cobra (unidentified)","description":"Naja sp."},
        {"name":"Gazelle, thomson's","description":"Gazella thompsonii"},
        {"name":"Tenrec, tailless","description":"Tenrec ecaudatus"},
        {"name":"Wolf, common","description":"Canis lupus"},
        {"name":"Carpet python","description":"Morelia spilotes variegata"},
        {"name":"Nuthatch, red-breasted","description":"Sitta canadensis"},
        {"name":"Orca","description":"Orcinus orca"},
        {"name":"Prairie falcon","description":"Falco mexicanus"},
        {"name":"Asian water buffalo","description":"Bubalus arnee"},
        {"name":"Campo flicker","description":"Colaptes campestroides"},
        {"name":"Parrot, hawk-headed","description":"Deroptyus accipitrinus"},
        {"name":"Moose","description":"Alces alces"},
        {"name":"Kookaburra, laughing","description":"Dacelo novaeguineae"},
        {"name":"African porcupine","description":"Hystrix cristata"},
        {"name":"Common rhea","description":"Rhea americana"},
        {"name":"Northern phalarope","description":"Phalaropus lobatus"},
        {"name":"Eagle, bald","description":"Haliaeetus leucocephalus"},
        {"name":"Tokay gecko","description":"Gekko gecko"},
        {"name":"Kori bustard","description":"Choriotis kori"},
        {"name":"Kangaroo, brush-tailed rat","description":"Bettongia penicillata"},
        {"name":"Baleen whale","description":"Eubalaena australis"},
        {"name":"Snake, carpet","description":"Morelia spilotes variegata"},
        {"name":"Wild boar","description":"Sus scrofa"},
        {"name":"Goanna lizard","description":"Varanus sp."},
        {"name":"Sloth, hoffman's","description":"Choloepus hoffmani"},
        {"name":"Potoroo","description":"Potorous tridactylus"},
        {"name":"Horned puffin","description":"Fratercula corniculata"},
        {"name":"Common genet","description":"Genetta genetta"},
        {"name":"Magellanic penguin","description":"Spheniscus magellanicus"},
        {"name":"White-necked stork","description":"Ciconia episcopus"},
        {"name":"Macaque, japanese","description":"Macaca fuscata"},
        {"name":"Bulbul, african red-eyed","description":"Pycnonotus nigricans"},
        {"name":"Goldeneye, barrows","description":"Bucephala clangula"},
        {"name":"Skunk, striped","description":"Mephitis mephitis"},
        {"name":"Zebra, common","description":"Equus burchelli"},
        {"name":"Eagle, crowned","description":"Spizaetus coronatus"},
        {"name":"Macaque, pig-tailed","description":"Macaca nemestrina"},
        {"name":"Four-spotted skimmer","description":"Libellula quadrimaculata"},
        {"name":"Phalarope, grey","description":"Phalaropus fulicarius"},
        {"name":"Vulture, turkey","description":"Cathartes aura"},
        {"name":"Lemming, collared","description":"Dicrostonyx groenlandicus"},
        {"name":"Pintail, white-cheeked","description":"Anas bahamensis"},
        {"name":"Buffalo, african","description":"Snycerus caffer"},
        {"name":"Magistrate black colobus","description":"Colobus guerza"},
        {"name":"Three-banded plover","description":"Charadrius tricollaris"},
        {"name":"Snake, tiger","description":"Notechis semmiannulatus"},
        {"name":"Porcupine, north american","description":"Erethizon dorsatum"},
        {"name":"Bird, magnificent frigate","description":"Fregata magnificans"},
        {"name":"African ground squirrel (unidentified)","description":"Xerus sp."},
        {"name":"Lesser flamingo","description":"Phoeniconaias minor"},
        {"name":"Phalarope, red","description":"Phalaropus fulicarius"},
        {"name":"Ornate rock dragon","description":"Ctenophorus ornatus"},
        {"name":"Kori bustard","description":"Choriotis kori"},
        {"name":"Dog, african wild","description":"Lycaon pictus"},
        {"name":"Turtle (unidentified)","description":"unavailable"},
        {"name":"African bush squirrel","description":"Paraxerus cepapi"},
        {"name":"Eastern boa constrictor","description":"Acrantophis madagascariensis"},
        {"name":"Western palm tanager (unidentified)","description":"unavailable"},
        {"name":"Lion, south american sea","description":"Otaria flavescens"},
        {"name":"Pintail, bahama","description":"Anas bahamensis"},
        {"name":"Bear, polar","description":"Ursus maritimus"},
        {"name":"Cormorant, great","description":"Phalacrocorax carbo"},
        {"name":"Salmon pink bird eater tarantula","description":"Lasiodora parahybana"},
        {"name":"Western patch-nosed snake","description":"Salvadora hexalepis"},
        {"name":"Tortoise, radiated","description":"Geochelone radiata"},
        {"name":"Verreaux's sifaka","description":"Propithecus verreauxi"},
        {"name":"Dromedary camel","description":"Camelus dromedarius"},
        {"name":"White-cheeked pintail","description":"Anas bahamensis"},
        {"name":"Paddy heron (unidentified)","description":"unavailable"},
        {"name":"Dragon, komodo","description":"Varanus komodensis"},
        {"name":"Asian elephant","description":"Elephas maximus bengalensis"},
        {"name":"Swamp deer","description":"Cervus duvauceli"},
        {"name":"Porcupine, tree","description":"Coendou prehensilis"},
        {"name":"American alligator","description":"Alligator mississippiensis"},
        {"name":"White-lipped peccary","description":"Tayassu pecari"},
        {"name":"Puku","description":"Kobus vardonii vardoni"},
        {"name":"Anteater, giant","description":"Myrmecophaga tridactyla"},
        {"name":"Pine snake (unidentified)","description":"Pituophis melanaleucus"},
        {"name":"Capuchin, black-capped","description":"Cebus apella"},
        {"name":"Python (unidentified)","description":"unavailable"},
        {"name":"Bird, pied butcher","description":"Cracticus nigroagularis"},
        {"name":"Armadillo, common long-nosed","description":"Dasypus novemcinctus"},
        {"name":"Cormorant, great","description":"Phalacrocorax carbo"},
        {"name":"Ring-necked pheasant","description":"Phasianus colchicus"},
        {"name":"Grizzly bear","description":"Ursus arctos"},
        {"name":"Bleeding heart monkey","description":"Theropithecus gelada"},
        {"name":"Vulture, black","description":"Aegypius tracheliotus"},
        {"name":"Ibis, puna","description":"Plegadis ridgwayi"},
        {"name":"South American meadowlark (unidentified)","description":"unavailable"},
        {"name":"Python (unidentified)","description":"unavailable"},
        {"name":"Pine snake (unidentified)","description":"Pituophis melanaleucus"},
        {"name":"Greater adjutant stork","description":"Leptoptilus dubius"},
        {"name":"House crow","description":"Corvus brachyrhynchos"},
        {"name":"Sloth, two-toed","description":"Choloepus hoffmani"},
        {"name":"Kangaroo, red","description":"Macropus rufus"},
        {"name":"African jacana","description":"Actophilornis africanus"},
        {"name":"Badger, eurasian","description":"Meles meles"},
        {"name":"Boa, cook's tree","description":"Corallus hortulanus cooki"},
        {"name":"Mouse, four-striped grass","description":"Rhabdomys pumilio"},
        {"name":"Yak","description":"Bos mutus"},
        {"name":"Water monitor","description":"Varanus salvator"},
        {"name":"Flicker, campo","description":"Colaptes campestroides"},
        {"name":"Chital","description":"Axis axis"},
        {"name":"Bunting, crested","description":"Melophus lathami"},
        {"name":"Sockeye salmon","description":"Oncorhynchus nerka"},
        {"name":"Crested barbet","description":"Trachyphonus vaillantii"},
        {"name":"Water monitor","description":"Varanus salvator"},
        {"name":"Giant heron","description":"Ardea golieth"},
        {"name":"Weaver, white-browed sparrow","description":"Plocepasser mahali"},
        {"name":"Tinamou, elegant crested","description":"Eudromia elegans"},
        {"name":"Opossum, american virginia","description":"Didelphis virginiana"},
        {"name":"Egyptian viper","description":"Naja haje"},
        {"name":"Black-backed magpie","description":"Gymnorhina tibicen"},
        {"name":"Mouse, four-striped grass","description":"Rhabdomys pumilio"},
        {"name":"Kalahari scrub robin","description":"Certotrichas paena"},
        {"name":"Cat, miner's","description":"Bassariscus astutus"},
        {"name":"Langur, hanuman","description":"Semnopithecus entellus"},
        {"name":"Green-winged macaw","description":"Ara chloroptera"},
        {"name":"Southern boubou","description":"Laniarius ferrugineus"},
        {"name":"Rhinoceros, square-lipped","description":"Ceratotherium simum"},
        {"name":"Chilean flamingo","description":"Phoenicopterus chilensis"},
        {"name":"Fox, arctic","description":"Alopex lagopus"},
        {"name":"Pallas's fish eagle","description":"Haliaeetus leucoryphus"},
        {"name":"Tiger","description":"Panthera tigris"},
        {"name":"Gull, kelp","description":"Larus dominicanus"},
        {"name":"Urial","description":"Ovis orientalis"},
        {"name":"Sloth, hoffman's","description":"Choloepus hoffmani"},
        {"name":"Heron, striated","description":"Butorides striatus"},
        {"name":"Deer, red","description":"Cervus elaphus"},
        {"name":"Guanaco","description":"Lama guanicoe"},
        {"name":"Mexican boa","description":"Boa constrictor mexicana"},
        {"name":"Wolf, mexican","description":"Canis lupus baileyi"},
        {"name":"Northern phalarope","description":"Phalaropus lobatus"},
        {"name":"Alligator, american","description":"Alligator mississippiensis"},
        {"name":"Egyptian cobra","description":"Naja haje"},
        {"name":"Blue wildebeest","description":"Connochaetus taurinus"},
        {"name":"Red-winged blackbird","description":"Agelaius phoeniceus"},
        {"name":"Buffalo, american","description":"Bison bison"},
        {"name":"Deer, red","description":"Cervus elaphus"},
        {"name":"Hawk, red-tailed","description":"Buteo jamaicensis"},
        {"name":"Blue fox","description":"Alopex lagopus"},
        {"name":"Legaan, Monitor (unidentified)","description":"Varanus sp."},
        {"name":"Kangaroo, brush-tailed rat","description":"Bettongia penicillata"},
        {"name":"Wildebeest, blue","description":"Connochaetus taurinus"},
        {"name":"Wattled crane","description":"Bugeranus caruncalatus"},
        {"name":"Buffalo, american","description":"Bison bison"},
        {"name":"Sociable weaver","description":"Philetairus socius"},
        {"name":"Pigeon, wood","description":"Columba palumbus"},
        {"name":"Green-winged macaw","description":"Ara chloroptera"},
        {"name":"Radiated tortoise","description":"Geochelone radiata"},
        {"name":"Parakeet, rose-ringed","description":"Psittacula krameri"},
        {"name":"Bustard, denham's","description":"Neotis denhami"},
        {"name":"Campo flicker","description":"Colaptes campestroides"},
        {"name":"Red-cheeked cordon bleu","description":"Uraeginthus bengalus"},
        {"name":"Common zebra","description":"Equus burchelli"},
        {"name":"Ovenbird","description":"Seiurus aurocapillus"},
        {"name":"Mallard","description":"Anas platyrhynchos"},
        {"name":"Rhea, greater","description":"Rhea americana"},
        {"name":"Shelduck, european","description":"Tadorna tadorna"},
        {"name":"Slender loris","description":"Loris tardigratus"},
        {"name":"Huron","description":"Galictis vittata"},
        {"name":"Eurasian red squirrel","description":"Sciurus vulgaris"},
        {"name":"Warthog","description":"Phacochoerus aethiopus"},
        {"name":"Oystercatcher, blackish","description":"Haematopus ater"},
        {"name":"Galapagos penguin","description":"Spheniscus mendiculus"},
        {"name":"Siskin, pine","description":"Carduelis pinus"},
        {"name":"Crocodile, nile","description":"Crocodylus niloticus"},
        {"name":"Bustard, denham's","description":"Neotis denhami"},
        {"name":"Little heron","description":"Butorides striatus"},
        {"name":"Hanuman langur","description":"Semnopithecus entellus"},
        {"name":"Knob-nosed goose","description":"Sarkidornis melanotos"},
        {"name":"Raven, cape","description":"Corvus albicollis"},
        {"name":"Small-toothed palm civet","description":"Arctogalidia trivirgata"},
        {"name":"Arboral spiny rat","description":"Echimys chrysurus"},
        {"name":"Possum, ring-tailed","description":"Pseudocheirus peregrinus"},
        {"name":"Ringtail","description":"Bassariscus astutus"},
        {"name":"Lapwing, southern","description":"Vanellus chilensis"},
        {"name":"Tiger cat","description":"Dasyurus maculatus"},
        {"name":"Blue-breasted cordon bleu","description":"Uraeginthus angolensis"},
        {"name":"California sea lion","description":"Zalophus californicus"},
        {"name":"Tern, white-winged black","description":"Chlidonias leucopterus"},
        {"name":"Mongoose, javan gold-spotted","description":"Herpestes javanicus"},
        {"name":"Baboon, olive","description":"Papio cynocephalus"},
        {"name":"Hornbill, southern ground","description":"Bucorvus leadbeateri"},
        {"name":"Gull, herring","description":"unavailable"},
        {"name":"Bee-eater, white-fronted","description":"Merops bullockoides"},
        {"name":"Dromedary camel","description":"Camelus dromedarius"},
        {"name":"Grizzly bear","description":"Ursus arctos"},
        {"name":"Chameleon (unidentified)","description":"Chamaelo sp."},
        {"name":"Sparrow, house","description":"Passer domesticus"},
        {"name":"Red sheep","description":"Ovis ammon"},
        {"name":"Red squirrel","description":"Tamiasciurus hudsonicus"},
        {"name":"Deer, black-tailed","description":"Odocoileus hemionus"},
        {"name":"Common zebra","description":"Equus burchelli"},
        {"name":"Indian tree pie","description":"Dendrocitta vagabunda"},
        {"name":"Deer, black-tailed","description":"Odocoileus hemionus"},
        {"name":"Cliffchat, mocking","description":"Thamnolaea cinnmomeiventris"},
        {"name":"Avocet, pied","description":"Recurvirostra avosetta"},
        {"name":"Bat, little brown","description":"Myotis lucifugus"},
        {"name":"Hummingbird (unidentified)","description":"unavailable"},
        {"name":"Wolf, timber","description":"Canis lupus lycaon"},
        {"name":"Eagle, african fish","description":"Haliaetus vocifer"},
        {"name":"Carpet snake","description":"Morelia spilotes variegata"},
        {"name":"Snake, racer","description":"Coluber constrictor"},
        {"name":"Black rhinoceros","description":"Diceros bicornis"},
        {"name":"Asian water buffalo","description":"Bubalus arnee"},
        {"name":"Blesbok","description":"Damaliscus dorcas"},
        {"name":"Eurasian red squirrel","description":"Sciurus vulgaris"},
        {"name":"Alligator, american","description":"Alligator mississippiensis"},
        {"name":"Coatimundi, ring-tailed","description":"Nasua nasua"},
        {"name":"Tasmanian devil","description":"Sarcophilus harrisii"},
        {"name":"Buffalo, african","description":"Snycerus caffer"},
        {"name":"Greylag goose","description":"Anser anser"},
        {"name":"Trumpeter, green-winged","description":"Psophia viridis"},
        {"name":"Red-winged hawk (unidentified)","description":"unavailable"},
        {"name":"Giraffe","description":"Giraffe camelopardalis"},
        {"name":"Gaur","description":"Bos frontalis"},
        {"name":"Cat, miner's","description":"Bassariscus astutus"},
        {"name":"Wallaby, bennett's","description":"Macropus rufogriseus"},
        {"name":"African skink","description":"Mabuya spilogaster"},
        {"name":"Mexican boa","description":"Boa constrictor mexicana"},
        {"name":"Magnificent frigate bird","description":"Fregata magnificans"},
        {"name":"Scarlet macaw","description":"Ara macao"},
        {"name":"Brush-tailed phascogale","description":"Phascogale tapoatafa"},
        {"name":"Pallas's fish eagle","description":"Haliaeetus leucoryphus"},
        {"name":"Groundhog","description":"Marmota monax"},
        {"name":"Wallaby, agile","description":"Macropus agilis"},
        {"name":"Gecko, barking","description":"Phylurus milli"},
        {"name":"Jaeger, long-tailed","description":"Stercorarius longicausus"},
        {"name":"White-tailed jackrabbit","description":"Lepus townsendii"},
        {"name":"Springhare","description":"Pedetes capensis"},
        {"name":"Dog, black-tailed prairie","description":"Cynomys ludovicianus"},
        {"name":"Polar bear","description":"Ursus maritimus"},
        {"name":"Crimson-breasted shrike","description":"Laniaurius atrococcineus"},
        {"name":"Meerkat","description":"Suricata suricatta"},
        {"name":"Little heron","description":"Butorides striatus"},
        {"name":"Hartebeest, coke's","description":"Alcelaphus buselaphus cokii"},
        {"name":"Glider, squirrel","description":"Petaurus norfolcensis"},
        {"name":"Magellanic penguin","description":"Spheniscus magellanicus"},
        {"name":"Heron, black-crowned night","description":"Nycticorax nycticorax"},
        {"name":"Indian tree pie","description":"Dendrocitta vagabunda"},
        {"name":"Macaw, green-winged","description":"Ara chloroptera"},
        {"name":"Northern phalarope","description":"Phalaropus lobatus"},
        {"name":"Moorhen, purple","description":"Porphyrio porphyrio"},
        {"name":"Springbuck","description":"Antidorcas marsupialis"},
        {"name":"Black curlew","description":"Haematopus ater"},
        {"name":"Black vulture","description":"Aegypius tracheliotus"},
        {"name":"Pallas's fish eagle","description":"Haliaeetus leucoryphus"},
        {"name":"Magistrate black colobus","description":"Colobus guerza"},
        {"name":"Python (unidentified)","description":"unavailable"},
        {"name":"Eastern fox squirrel","description":"Sciurus niger"},
        {"name":"Mocking cliffchat","description":"Thamnolaea cinnmomeiventris"},
        {"name":"Flamingo, chilean","description":"Phoenicopterus chilensis"},
        {"name":"Bear, polar","description":"Ursus maritimus"},
        {"name":"Black-throated cardinal","description":"Paroaria gularis"},
        {"name":"Fringe-eared oryx","description":"Oryx gazella callotis"},
        {"name":"Alligator, mississippi","description":"Alligator mississippiensis"},
        {"name":"Peregrine falcon","description":"Falco peregrinus"},
        {"name":"Gazelle, grant's","description":"Gazella granti"},
        {"name":"Olive baboon","description":"Papio cynocephalus"},
        {"name":"Curve-billed thrasher","description":"Toxostoma curvirostre"},
        {"name":"Glossy ibis","description":"Plegadis falcinellus"},
        {"name":"Squirrel, eastern fox","description":"Sciurus niger"},
        {"name":"Tawny eagle","description":"Anitibyx armatus"},
        {"name":"Blue catfish","description":"Ictalurus furcatus"},
        {"name":"African skink","description":"Mabuya spilogaster"},
        {"name":"Baboon, savanna","description":"Papio cynocephalus"},
        {"name":"Yellow-brown sungazer","description":"Cordylus giganteus"},
        {"name":"Boubou, southern","description":"Laniarius ferrugineus"},
        {"name":"Southern lapwing","description":"Vanellus chilensis"},
        {"name":"Chilean flamingo","description":"Phoenicopterus chilensis"},
        {"name":"Downy woodpecker","description":"Picoides pubescens"},
        {"name":"Macaw, blue and yellow","description":"Ara ararauna"},
        {"name":"Kalahari scrub robin","description":"Certotrichas paena"},
        {"name":"Australian masked owl","description":"Tyto novaehollandiae"},
        {"name":"Levaillant's barbet","description":"Trachyphonus vaillantii"},
        {"name":"Iguana, marine","description":"Amblyrhynchus cristatus"},
        {"name":"Dragonfly, russian","description":"Libellula quadrimaculata"},
        {"name":"North American red fox","description":"Vulpes vulpes"},
        {"name":"American Virginia opossum","description":"Didelphis virginiana"},
        {"name":"Egyptian vulture","description":"Neophron percnopterus"},
        {"name":"Pintail, bahama","description":"Anas bahamensis"},
        {"name":"Bear, polar","description":"Ursus maritimus"},
        {"name":"Tyrant flycatcher","description":"Myiarchus tuberculifer"},
        {"name":"Cormorant, king","description":"Phalacrocorax albiventer"},
        {"name":"White-necked raven","description":"Corvus albicollis"},
        {"name":"Little brown bat","description":"Myotis lucifugus"},
        {"name":"Cockatoo, red-tailed","description":"Calyptorhynchus magnificus"},
        {"name":"Lion, steller sea","description":"Eumetopias jubatus"},
        {"name":"Tiger snake","description":"Notechis semmiannulatus"},
        {"name":"Pelican, australian","description":"Pelecanus conspicillatus"},
        {"name":"Land iguana","description":"Conolophus subcristatus"},
        {"name":"Asian red fox","description":"Vulpes vulpes"},
        {"name":"Red-necked wallaby","description":"Macropus rufogriseus"},
        {"name":"Water legaan","description":"Varanus salvator"},
        {"name":"Pigeon, wood","description":"Columba palumbus"},
        {"name":"Porcupine, african","description":"Hystrix cristata"},
        {"name":"Bat, little brown","description":"Myotis lucifugus"},
        {"name":"Robin, white-throated","description":"Irania gutteralis"},
        {"name":"Javanese cormorant","description":"Phalacrocorax niger"},
        {"name":"Lizard, desert spiny","description":"Sceloporus magister"},
        {"name":"Gray duiker","description":"Sylvicapra grimma"},
        {"name":"Hyena, striped","description":"Hyaena hyaena"},
        {"name":"Water monitor","description":"Varanus salvator"},
        {"name":"Water moccasin","description":"Agkistrodon piscivorus"},
        {"name":"Silver-backed fox","description":"Vulpes chama"},
        {"name":"Barbet, levaillant's","description":"Trachyphonus vaillantii"},
        {"name":"Gecko, barking","description":"Phylurus milli"},
        {"name":"Stilt, black-winged","description":"Himantopus himantopus"},
        {"name":"Giant heron","description":"Ardea golieth"},
        {"name":"Stork, greater adjutant","description":"Leptoptilus dubius"},
        {"name":"Blue and yellow macaw","description":"Ara ararauna"},
        {"name":"Owl, great horned","description":"Bubo virginianus"},
        {"name":"Marabou stork","description":"Leptoptilos crumeniferus"},
        {"name":"Beaver, american","description":"Castor canadensis"},
        {"name":"Paddy heron (unidentified)","description":"unavailable"},
        {"name":"Common long-nosed armadillo","description":"Dasypus novemcinctus"},
        {"name":"Sacred ibis","description":"Threskionis aethiopicus"},
        {"name":"Frog (unidentified)","description":"Rana sp."},
        {"name":"Antelope, sable","description":"Hippotragus niger"},
        {"name":"Vulture, oriental white-backed","description":"Gyps bengalensis"},
        {"name":"Capuchin, weeper","description":"Cebus nigrivittatus"},
        {"name":"Desert kangaroo rat","description":"Dipodomys deserti"},
        {"name":"Pie, rufous tree","description":"Dendrocitta vagabunda"},
        {"name":"Red-billed toucan","description":"Ramphastos tucanus"},
        {"name":"Squirrel, european red","description":"Sciurus vulgaris"},
        {"name":"Emerald-spotted wood dove","description":"Turtur chalcospilos"},
        {"name":"Long-tailed jaeger","description":"Stercorarius longicausus"},
        {"name":"Blackbuck","description":"Antilope cervicapra"},
        {"name":"Downy woodpecker","description":"Picoides pubescens"},
        {"name":"Kelp gull","description":"Larus dominicanus"},
        {"name":"Sable antelope","description":"Hippotragus niger"},
        {"name":"Common wallaroo","description":"Macropus robustus"},
        {"name":"Red-shouldered glossy starling","description":"Lamprotornis nitens"},
        {"name":"Little grebe","description":"Tachybaptus ruficollis"},
        {"name":"Leopard, indian","description":"Panthera pardus"},
        {"name":"Suricate","description":"Suricata suricatta"},
        {"name":"Tiger","description":"Panthera tigris"},
        {"name":"Eastern indigo snake","description":"Drymarchon corias couperi"},
        {"name":"Blue catfish","description":"Ictalurus furcatus"},
        {"name":"Crowned eagle","description":"Spizaetus coronatus"},
        {"name":"Common pheasant","description":"Phasianus colchicus"},
        {"name":"Red phalarope","description":"Phalaropus fulicarius"},
        {"name":"Bee-eater, white-fronted","description":"Merops bullockoides"},
        {"name":"Tortoise, burmese brown mountain","description":"Manouria emys"},
        {"name":"Shelduck, european","description":"Tadorna tadorna"},
        {"name":"Least chipmunk","description":"Eutamias minimus"},
        {"name":"Bateleur eagle","description":"Terathopius ecaudatus"},
        {"name":"Nile crocodile","description":"Crocodylus niloticus"},
        {"name":"Yellow mongoose","description":"Cynictis penicillata"},
        {"name":"Snake, buttermilk","description":"Coluber constrictor"},
        {"name":"Swallow (unidentified)","description":"unavailable"},
        {"name":"Heron, striated","description":"Butorides striatus"},
        {"name":"Hartebeest, red","description":"Alcelaphus buselaphus caama"},
        {"name":"Pied avocet","description":"Recurvirostra avosetta"},
        {"name":"Potoroo","description":"Potorous tridactylus"},
        {"name":"Canada goose","description":"Branta canadensis"},
        {"name":"Ring-necked pheasant","description":"Phasianus colchicus"},
        {"name":"Galapagos albatross","description":"Diomedea irrorata"},
        {"name":"Huron","description":"Galictis vittata"},
        {"name":"Yellow mongoose","description":"Cynictis penicillata"},
        {"name":"Grouse, sage","description":"Centrocercus urophasianus"},
        {"name":"Common zebra","description":"Equus burchelli"},
        {"name":"Brown antechinus","description":"Antechinus flavipes"},
        {"name":"Margay","description":"Felis wiedi or Leopardus weidi"},
        {"name":"Dragon, netted rock","description":"Ctenophorus ornatus"},
        {"name":"Flicker, campo","description":"Colaptes campestroides"},
        {"name":"Snake, eastern indigo","description":"Drymarchon corias couperi"},
        {"name":"Cockatoo, long-billed","description":"Cacatua tenuirostris"},
        {"name":"African bush squirrel","description":"Paraxerus cepapi"},
        {"name":"Black rhinoceros","description":"Diceros bicornis"},
        {"name":"Seal, northern elephant","description":"Mirounga angustirostris"},
        {"name":"Rhinoceros, white","description":"Ceratotherium simum"},
        {"name":"Starling, greater blue-eared","description":"Lamprotornis chalybaeus"},
        {"name":"Hippopotamus","description":"Hippopotamus amphibius"},
        {"name":"Whale, killer","description":"Orcinus orca"},
        {"name":"Dunnart, fat-tailed","description":"Smithopsis crassicaudata"},
        {"name":"Red-billed buffalo weaver","description":"Bubalornis niger"},
        {"name":"Indian leopard","description":"Panthera pardus"},
        {"name":"Crown of thorns starfish","description":"Acanthaster planci"},
        {"name":"Monster, gila","description":"Heloderma horridum"},
        {"name":"Lesser masked weaver","description":"Ploceus intermedius"},
        {"name":"Penguin, fairy","description":"Eudyptula minor"},
        {"name":"Serval","description":"Felis serval"},
        {"name":"White-nosed coatimundi","description":"Nasua narica"},
        {"name":"African wild dog","description":"Lycaon pictus"},
        {"name":"Water legaan","description":"Varanus salvator"},
        {"name":"Fat-tailed dunnart","description":"Smithopsis crassicaudata"},
        {"name":"Brush-tailed rat kangaroo","description":"Bettongia penicillata"},
        {"name":"Barking gecko","description":"Phylurus milli"},
        {"name":"Indian mynah","description":"Acridotheres tristis"},
        {"name":"Kangaroo, black-faced","description":"Macropus fuliginosus"},
        {"name":"Macaw, red and blue","description":"Ara chloroptera"},
        {"name":"Phalarope, grey","description":"Phalaropus fulicarius"},
        {"name":"Gazelle, thomson's","description":"Gazella thompsonii"},
        {"name":"Carpet snake","description":"Morelia spilotes variegata"},
        {"name":"Pelican, brown","description":"Pelecanus occidentalis"},
        {"name":"Hyrax","description":"Dendrohyrax brucel"},
        {"name":"Goose, cape barren","description":"Cereopsis novaehollandiae"},
        {"name":"Colobus, white-mantled","description":"Colobus guerza"},
        {"name":"Silver-backed fox","description":"Vulpes chama"},
        {"name":"Grant's gazelle","description":"Gazella granti"},
        {"name":"Jabiru stork","description":"Ephippiorhynchus mycteria"},
        {"name":"African ground squirrel (unidentified)","description":"Xerus sp."},
        {"name":"Heron, green-backed","description":"Butorides striatus"},
        {"name":"Eastern white pelican","description":"Pelecans onocratalus"},
        {"name":"Crested barbet","description":"Trachyphonus vaillantii"},
        {"name":"Peregrine falcon","description":"Falco peregrinus"},
        {"name":"Yellow-brown sungazer","description":"Cordylus giganteus"},
        {"name":"European red squirrel","description":"Sciurus vulgaris"},
        {"name":"Kori bustard","description":"Choriotis kori"},
        {"name":"Kingfisher, pied","description":"Ceryle rudis"},
        {"name":"Emerald green tree boa","description":"Boa caninus"},
        {"name":"Oriental short-clawed otter","description":"Aonyx cinerea"},
        {"name":"Argalis","description":"Ovis ammon"},
        {"name":"Steenbok","description":"Raphicerus campestris"},
        {"name":"Short-beaked echidna","description":"Tachyglossus aculeatus"},
        {"name":"Red and blue macaw","description":"Ara chloroptera"},
        {"name":"Mourning collared dove","description":"Streptopelia decipiens"},
        {"name":"Red phalarope","description":"Phalaropus fulicarius"},
        {"name":"Desert spiny lizard","description":"Sceloporus magister"},
        {"name":"Tortoise, burmese black mountain","description":"Manouria emys"},
        {"name":"Kirk's dik dik","description":"Madoqua kirkii"},
        {"name":"Porcupine, prehensile-tailed","description":"Coendou prehensilis"},
        {"name":"Chameleon (unidentified)","description":"Chamaelo sp."},
        {"name":"Otter, cape clawless","description":"Aonyx capensis"},
        {"name":"Vicuna","description":"Vicugna vicugna"},
        {"name":"Openbill, asian","description":"Anastomus oscitans"},
        {"name":"Gray duiker","description":"Sylvicapra grimma"},
        {"name":"Snake-necked turtle","description":"Chelodina longicollis"},
        {"name":"Common wolf","description":"Canis lupus"},
        {"name":"Turkey, common","description":"Meleagris gallopavo"},
        {"name":"Gila monster","description":"Heloderma horridum"},
        {"name":"Two-toed tree sloth","description":"Choloepus hoffmani"},
        {"name":"Rhesus macaque","description":"Macaca mulatta"},
        {"name":"Deer, roe","description":"Capreolus capreolus"},
        {"name":"Shelduck, european","description":"Tadorna tadorna"},
        {"name":"Red-billed toucan","description":"Ramphastos tucanus"},
        {"name":"Prairie falcon","description":"Falco mexicanus"},
        {"name":"Southern sea lion","description":"Otaria flavescens"},
        {"name":"Yellow-crowned night heron","description":"Nyctanassa violacea"},
        {"name":"California sea lion","description":"Zalophus californicus"},
        {"name":"Antelope, roan","description":"Hippotragus equinus"},
        {"name":"Stork, yellow-billed","description":"Mycteria ibis"},
        {"name":"Western grey kangaroo","description":"Macropus fuliginosus"},
        {"name":"Brindled gnu","description":"Connochaetus taurinus"},
        {"name":"Tawny frogmouth","description":"Podargus strigoides"},
        {"name":"Pheasant, common","description":"Phasianus colchicus"},
        {"name":"Polar bear","description":"Ursus maritimus"},
        {"name":"Lizard, frilled","description":"Chlamydosaurus kingii"},
        {"name":"Common eland","description":"Taurotagus oryx"},
        {"name":"Tawny frogmouth","description":"Podargus strigoides"},
        {"name":"Vicuna","description":"Vicugna vicugna"},
        {"name":"Crab-eating raccoon","description":"Procyon cancrivorus"},
        {"name":"Red-winged hawk (unidentified)","description":"unavailable"},
        {"name":"Marine iguana","description":"Amblyrhynchus cristatus"},
        {"name":"Cat, jungle","description":"Felis chaus"},
        {"name":"Cat, african wild","description":"Felis silvestris lybica"},
        {"name":"Tailless tenrec","description":"Tenrec ecaudatus"},
        {"name":"Potoroo","description":"Potorous tridactylus"},
        {"name":"Little brown bat","description":"Myotis lucifugus"},
        {"name":"Snowy owl","description":"Nyctea scandiaca"},
        {"name":"Red lava crab","description":"Graspus graspus"},
        {"name":"African polecat","description":"Ictonyx striatus"},
        {"name":"Ground monitor (unidentified)","description":"Varanus sp."},
        {"name":"Ibex","description":"Capra ibex"},
        {"name":"Penguin, galapagos","description":"Spheniscus mendiculus"},
        {"name":"Laughing kookaburra","description":"Dacelo novaeguineae"},
        {"name":"Chimpanzee","description":"Pan troglodytes"},
        {"name":"Stork, white","description":"Ciconia ciconia"},
        {"name":"Bird, secretary","description":"Sagittarius serpentarius"},
        {"name":"Thirteen-lined squirrel","description":"Spermophilus tridecemlineatus"},
        {"name":"Grouse, greater sage","description":"Centrocercus urophasianus"},
        {"name":"Mara","description":"Dolichitus patagonum"},
        {"name":"African porcupine","description":"Hystrix cristata"},
        {"name":"Hoopoe, eurasian","description":"Upupa epops"},
        {"name":"Cougar","description":"Felis concolor"},
        {"name":"Elephant, asian","description":"Elephas maximus bengalensis"},
        {"name":"Blue-tongued lizard","description":"Tiliqua scincoides"},
        {"name":"Waxbill, violet-eared","description":"Uraeginthus granatina"},
        {"name":"Goose, snow","description":"Anser caerulescens"},
        {"name":"Red-billed buffalo weaver","description":"Bubalornis niger"},
        {"name":"Mourning collared dove","description":"Streptopelia decipiens"},
        {"name":"Crab (unidentified)","description":"unavailable"},
        {"name":"Owl, snowy","description":"Nyctea scandiaca"},
        {"name":"Red squirrel","description":"Tamiasciurus hudsonicus"},
        {"name":"Ibis, sacred","description":"Threskionis aethiopicus"},
        {"name":"Jabiru stork","description":"Ephippiorhynchus mycteria"},
        {"name":"Platypus","description":"Ornithorhynchus anatinus"},
        {"name":"American Virginia opossum","description":"Didelphis virginiana"},
        {"name":"Blackbuck","description":"Antilope cervicapra"},
        {"name":"Common wolf","description":"Canis lupus"},
        {"name":"Aardwolf","description":"Proteles cristatus"},
        {"name":"Pintail, white-cheeked","description":"Anas bahamensis"},
        {"name":"Macaque, rhesus","description":"Macaca mulatta"},
        {"name":"Nighthawk, common","description":"Chordeiles minor"},
        {"name":"Mexican wolf","description":"Canis lupus baileyi"},
        {"name":"Yellow-headed caracara","description":"Milvago chimachima"},
        {"name":"Sambar","description":"Cervus unicolor"},
        {"name":"Mouflon","description":"Ovis musimon"},
        {"name":"Grey mouse lemur","description":"Microcebus murinus"},
        {"name":"Great white pelican","description":"Pelecans onocratalus"},
        {"name":"Gazelle, thomson's","description":"Gazella thompsonii"},
        {"name":"Netted rock dragon","description":"Ctenophorus ornatus"},
        {"name":"Lorikeet, scaly-breasted","description":"Trichoglossus chlorolepidotus"},
        {"name":"Bat, asian false vampire","description":"Megaderma spasma"},
        {"name":"Chickadee, black-capped","description":"Parus atricapillus"},
        {"name":"Macaque, bonnet","description":"Macaca radiata"},
        {"name":"Sheep, stone","description":"Ovis dalli stonei"},
        {"name":"Antelope, roan","description":"Hippotragus equinus"},
        {"name":"Egyptian cobra","description":"Naja haje"},
        {"name":"Sloth, pale-throated three-toed","description":"Bradypus tridactylus"},
        {"name":"Praying mantis (unidentified)","description":"unavailable"},
        {"name":"Dassie","description":"Dendrohyrax brucel"},
        {"name":"Legaan, Monitor (unidentified)","description":"Varanus sp."},
        {"name":"Pine snake (unidentified)","description":"Pituophis melanaleucus"},
        {"name":"Harbor seal","description":"Phoca vitulina"},
        {"name":"Onager","description":"Equus hemionus"},
        {"name":"Porcupine, prehensile-tailed","description":"Coendou prehensilis"},
        {"name":"Fox, bat-eared","description":"Otocyon megalotis"},
        {"name":"Hyena, brown","description":"Hyaena brunnea"},
        {"name":"Duck, white-faced whistling","description":"Dendrocygna viduata"},
        {"name":"American black bear","description":"Ursus americanus"},
        {"name":"Crow, american","description":"Corvus brachyrhynchos"},
        {"name":"Sable antelope","description":"Hippotragus niger"},
        {"name":"Mexican beaded lizard","description":"Heloderma horridum"},
        {"name":"Civet, common palm","description":"Paradoxurus hermaphroditus"},
        {"name":"Greater sage grouse","description":"Centrocercus urophasianus"},
        {"name":"Snake (unidentified)","description":"unavailable"},
        {"name":"Alligator, mississippi","description":"Alligator mississippiensis"},
        {"name":"Tortoise, desert","description":"Gopherus agassizii"},
        {"name":"Squirrel, african bush","description":"Paraxerus cepapi"},
        {"name":"Legaan, Monitor (unidentified)","description":"Varanus sp."},
        {"name":"African buffalo","description":"Snycerus caffer"},
        {"name":"Wallaroo, common","description":"Macropus robustus"},
        {"name":"African polecat","description":"Ictonyx striatus"},
        {"name":"Amazon parrot (unidentified)","description":"Amazona sp."},
        {"name":"House sparrow","description":"Passer domesticus"},
        {"name":"Ring dove","description":"Columba palumbus"},
        {"name":"Goose, cereopsis","description":"Cereopsis novaehollandiae"},
        {"name":"North American porcupine","description":"Erethizon dorsatum"},
        {"name":"Malachite kingfisher","description":"Corythornis cristata"},
        {"name":"Turkey, common","description":"Meleagris gallopavo"},
        {"name":"Skink, african","description":"Mabuya spilogaster"},
        {"name":"Salmon, sockeye","description":"Oncorhynchus nerka"},
        {"name":"Eastern white pelican","description":"Pelecans onocratalus"},
        {"name":"Spotted hyena","description":"Crocuta crocuta"},
        {"name":"Chital","description":"Axis axis"},
        {"name":"Beaver, eurasian","description":"Castor fiber"},
        {"name":"Giant girdled lizard","description":"Cordylus giganteus"},
        {"name":"Albatross, galapagos","description":"Diomedea irrorata"},
        {"name":"Golden jackal","description":"Canis aureus"},
        {"name":"Western spotted skunk","description":"Spilogale gracilis"},
        {"name":"Crane, black-crowned","description":"Balearica pavonina"},
        {"name":"Short-beaked echidna","description":"Tachyglossus aculeatus"},
        {"name":"Macaque, pig-tailed","description":"Macaca nemestrina"},
        {"name":"Ground monitor (unidentified)","description":"Varanus sp."},
        {"name":"Woodpecker, downy","description":"Picoides pubescens"},
        {"name":"Swainson's francolin","description":"Francolinus swainsonii"},
        {"name":"Vulture, oriental white-backed","description":"Gyps bengalensis"},
        {"name":"Western palm tanager (unidentified)","description":"unavailable"},
        {"name":"Steller sea lion","description":"Eumetopias jubatus"},
        {"name":"Lion, steller sea","description":"Eumetopias jubatus"},
        {"name":"Ringtail cat","description":"Bassariscus astutus"},
        {"name":"Possum, golden brush-tailed","description":"Trichosurus vulpecula"},
        {"name":"Hyena, spotted","description":"Crocuta crocuta"},
        {"name":"Galapagos dove","description":"Zenaida galapagoensis"},
        {"name":"Hudsonian godwit","description":"Limosa haemastica"},
        {"name":"Yellow mongoose","description":"Cynictis penicillata"},
        {"name":"Small Indian mongoose","description":"Herpestes javanicus"},
        {"name":"Heron, green","description":"Butorides striatus"},
        {"name":"Waterbuck, defassa","description":"Kobus defassa"},
        {"name":"European shelduck","description":"Tadorna tadorna"},
        {"name":"Reedbuck, bohor","description":"Redunca redunca"},
        {"name":"Leadbeateri's ground hornbill","description":"Bucorvus leadbeateri"},
        {"name":"Black-throated butcher bird","description":"Cracticus nigroagularis"},
        {"name":"Cow, scottish highland","description":"Bos taurus"},
        {"name":"Beaver, european","description":"Castor fiber"},
        {"name":"White-mantled colobus","description":"Colobus guerza"},
        {"name":"Cape fox","description":"Vulpes chama"},
        {"name":"Tropical buckeye butterfly","description":"Junonia genoveua"},
        {"name":"Raven, cape","description":"Corvus albicollis"},
        {"name":"Indian red admiral","description":"Vanessa indica"},
        {"name":"Capuchin, weeper","description":"Cebus nigrivittatus"},
        {"name":"Mourning collared dove","description":"Streptopelia decipiens"},
        {"name":"Greater rhea","description":"Rhea americana"},
        {"name":"Rhesus macaque","description":"Macaca mulatta"},
        {"name":"White-headed vulture","description":"Aegypius occipitalis"},
        {"name":"Egret, snowy","description":"Egretta thula"},
        {"name":"Barking gecko","description":"Phylurus milli"},
        {"name":"Frogmouth, tawny","description":"Podargus strigoides"},
        {"name":"Western pygmy possum","description":"Cercatetus concinnus"},
        {"name":"Beaver, eurasian","description":"Castor fiber"},
        {"name":"European spoonbill","description":"Platalea leucordia"},
        {"name":"Macaw, blue and gold","description":"Ara ararauna"},
        {"name":"Dusky rattlesnake","description":"Crotalus triseriatus"},
        {"name":"Collared lizard","description":"Crotaphytus collaris"},
        {"name":"Carpet python","description":"Morelia spilotes variegata"},
        {"name":"Crocodile, nile","description":"Crocodylus niloticus"},
        {"name":"Seal, northern elephant","description":"Mirounga angustirostris"},
        {"name":"Miner's cat","description":"Bassariscus astutus"},
        {"name":"Long-nosed bandicoot","description":"Perameles nasuta"},
        {"name":"Dog, raccoon","description":"Nyctereutes procyonoides"},
        {"name":"Squirrel, eastern fox","description":"Sciurus niger"},
        {"name":"Mongoose, javan gold-spotted","description":"Herpestes javanicus"},
        {"name":"Comb duck","description":"Sarkidornis melanotos"},
        {"name":"Grey lourie","description":"Lorythaixoides concolor"},
        {"name":"Olive baboon","description":"Papio cynocephalus"},
        {"name":"Malabar squirrel","description":"Ratufa indica"},
        {"name":"Snake, tiger","description":"Notechis semmiannulatus"},
        {"name":"Boa, emerald green tree","description":"Boa caninus"},
        {"name":"Pale white-eye","description":"Zosterops pallidus"},
        {"name":"Chimpanzee","description":"Pan troglodytes"},
        {"name":"Puma","description":"Felis concolor"},
        {"name":"Madagascar fruit bat","description":"Pteropus rufus"},
        {"name":"Vervet monkey","description":"Cercopithecus aethiops"},
        {"name":"Gull, silver","description":"Larus novaehollandiae"},
        {"name":"Lorikeet, scaly-breasted","description":"Trichoglossus chlorolepidotus"},
        {"name":"White-winged tern","description":"Chlidonias leucopterus"},
        {"name":"Prehensile-tailed porcupine","description":"Coendou prehensilis"},
        {"name":"Fringe-eared oryx","description":"Oryx gazella callotis"},
        {"name":"Goose, egyptian","description":"Alopochen aegyptiacus"},
        {"name":"Onager","description":"Equus hemionus"},
        {"name":"Black-faced kangaroo","description":"Macropus fuliginosus"},
        {"name":"Tiger cat","description":"Dasyurus maculatus"},
        {"name":"Silver-backed fox","description":"Vulpes chama"},
        {"name":"Shelduck, european","description":"Tadorna tadorna"},
        {"name":"Monitor, white-throated","description":"Varanus albigularis"},
        {"name":"Red phalarope","description":"Phalaropus fulicarius"},
        {"name":"Possum, pygmy","description":"Acrobates pygmaeus"},
        {"name":"Chestnut weaver","description":"Ploceus rubiginosus"},
        {"name":"Ant (unidentified)","description":"unavailable"},
        {"name":"Crane, black-crowned","description":"Balearica pavonina"},
        {"name":"Gazer, sun","description":"Cordylus giganteus"},
        {"name":"Legaan, Monitor (unidentified)","description":"Varanus sp."},
        {"name":"Common pheasant","description":"Phasianus colchicus"},
        {"name":"Lion, australian sea","description":"Neophoca cinerea"},
        {"name":"Black curlew","description":"Haematopus ater"},
        {"name":"African skink","description":"Mabuya spilogaster"},
        {"name":"Two-banded monitor","description":"Varanus salvator"},
        {"name":"Aardwolf","description":"Proteles cristatus"},
        {"name":"Deer, red","description":"Cervus elaphus"},
        {"name":"Bald eagle","description":"Haliaeetus leucocephalus"},
        {"name":"Cat, long-tailed spotted","description":"Felis wiedi or Leopardus weidi"},
        {"name":"Otter, small-clawed","description":"Aonyx cinerea"},
        {"name":"Rhea, greater","description":"Rhea americana"},
        {"name":"Hudsonian godwit","description":"Limosa haemastica"},
        {"name":"Javanese cormorant","description":"Phalacrocorax niger"},
        {"name":"Cardinal, black-throated","description":"Paroaria gularis"},
        {"name":"Tortoise, indian star","description":"Geochelone elegans"},
        {"name":"Monitor, water","description":"Varanus salvator"},
        {"name":"Huron","description":"Galictis vittata"},
        {"name":"Oystercatcher, blackish","description":"Haematopus ater"},
        {"name":"Kiskadee, great","description":"Pitangus sulphuratus"},
        {"name":"Mongoose, eastern dwarf","description":"Helogale undulata"},
        {"name":"Kiskadee, great","description":"Pitangus sulphuratus"},
        {"name":"Gorilla, western lowland","description":"Gorilla gorilla"},
        {"name":"Dove, galapagos","description":"Zenaida galapagoensis"},
        {"name":"Hummingbird (unidentified)","description":"unavailable"},
        {"name":"Woodcock, american","description":"Scolopax minor"},
        {"name":"Ring-necked pheasant","description":"Phasianus colchicus"},
        {"name":"Kelp gull","description":"Larus dominicanus"},
        {"name":"Squirrel, eurasian red","description":"Sciurus vulgaris"},
        {"name":"Goose, cape barren","description":"Cereopsis novaehollandiae"},
        {"name":"Cormorant, king","description":"Phalacrocorax albiventer"},
        {"name":"Bustard, stanley","description":"Neotis denhami"},
        {"name":"Smith's bush squirrel","description":"Paraxerus cepapi"},
        {"name":"Eland, common","description":"Taurotagus oryx"},
        {"name":"Mongoose, yellow","description":"Cynictis penicillata"},
        {"name":"Cobra, cape","description":"Naja nivea"},
        {"name":"Fisher","description":"Martes pennanti"},
        {"name":"Squirrel, golden-mantled ground","description":"Spermophilus lateralis"},
        {"name":"Field flicker","description":"Colaptes campestroides"},
        {"name":"Gray heron","description":"Ardea cinerea"},
        {"name":"Mynah, indian","description":"Acridotheres tristis"},
        {"name":"Secretary bird","description":"Sagittarius serpentarius"},
        {"name":"Frilled lizard","description":"Chlamydosaurus kingii"},
        {"name":"Burchell's gonolek","description":"Laniaurius atrococcineus"},
        {"name":"Arctic fox","description":"Alopex lagopus"},
        {"name":"Nubian bee-eater","description":"Merops nubicus"},
        {"name":"Baleen whale","description":"Eubalaena australis"},
        {"name":"Macaque, pig-tailed","description":"Macaca nemestrina"},
        {"name":"Brocket, brown","description":"Mazama gouazoubira"},
        {"name":"Long-necked turtle","description":"Chelodina longicollis"},
        {"name":"Monitor lizard (unidentified)","description":"Varanus sp."},
        {"name":"Neotropic cormorant","description":"Phalacrocorax brasilianus"},
        {"name":"Eagle, golden","description":"Aquila chrysaetos"},
        {"name":"Deer, white-tailed","description":"Odocoilenaus virginianus"},
        {"name":"Mongoose, javan gold-spotted","description":"Herpestes javanicus"},
        {"name":"Stork, white","description":"Ciconia ciconia"},
        {"name":"Slender loris","description":"Loris tardigratus"},
        {"name":"Impala","description":"Aepyceros mylampus"},
        {"name":"Squirrel, indian giant","description":"Ratufa indica"},
        {"name":"Sage grouse","description":"Centrocercus urophasianus"},
        {"name":"Puma","description":"Felis concolor"},
        {"name":"Striated heron","description":"Butorides striatus"},
        {"name":"African wild dog","description":"Lycaon pictus"},
        {"name":"Godwit, hudsonian","description":"Limosa haemastica"},
        {"name":"Cat, ringtail","description":"Bassariscus astutus"},
        {"name":"Squirrel, european red","description":"Sciurus vulgaris"},
        {"name":"Square-lipped rhinoceros","description":"Ceratotherium simum"},
        {"name":"Squirrel, african bush","description":"Paraxerus cepapi"},
        {"name":"Spotted-tailed quoll","description":"Dasyurus maculatus"},
        {"name":"Brown capuchin","description":"Cebus apella"},
        {"name":"Bleu, blue-breasted cordon","description":"Uraeginthus angolensis"},
        {"name":"Iguana, common green","description":"Iguana iguana"},
        {"name":"Bushbuck","description":"Tragelaphus scriptus"},
        {"name":"Swainson's francolin","description":"Francolinus swainsonii"},
        {"name":"Phalarope, red-necked","description":"Phalaropus lobatus"},
        {"name":"Glossy starling (unidentified)","description":"Lamprotornis sp."},
        {"name":"Arctic hare","description":"Lepus arcticus"},
        {"name":"Black kite","description":"Milvus migrans"},
        {"name":"Cormorant, pied","description":"Phalacrocorax varius"},
        {"name":"Caiman, spectacled","description":"Caiman crocodilus"},
        {"name":"White-lipped peccary","description":"Tayassu pecari"},
        {"name":"Honey badger","description":"Mellivora capensis"},
        {"name":"Grenadier, common","description":"Uraeginthus granatina"},
        {"name":"Common pheasant","description":"Phasianus colchicus"},
        {"name":"Dove, emerald-spotted wood","description":"Turtur chalcospilos"},
        {"name":"Monitor, water","description":"Varanus salvator"},
        {"name":"Gull, lava","description":"Larus fuliginosus"},
        {"name":"Thirteen-lined squirrel","description":"Spermophilus tridecemlineatus"},
        {"name":"Short-nosed bandicoot","description":"Isoodon obesulus"},
        {"name":"Giant armadillo","description":"Priodontes maximus"},
        {"name":"Red phalarope","description":"Phalaropus fulicarius"},
        {"name":"Blue crane","description":"Anthropoides paradisea"},
        {"name":"Rhinoceros, square-lipped","description":"Ceratotherium simum"},
        {"name":"Racer, blue","description":"Coluber constrictor foxii"},
        {"name":"Common zebra","description":"Equus burchelli"},
        {"name":"Little grebe","description":"Tachybaptus ruficollis"},
        {"name":"Black bear","description":"Ursus americanus"},
        {"name":"Shelduck, european","description":"Tadorna tadorna"},
        {"name":"Black curlew","description":"Haematopus ater"},
        {"name":"African jacana","description":"Actophilornis africanus"},
        {"name":"Giraffe","description":"Giraffe camelopardalis"},
        {"name":"Southern screamer","description":"Chauna torquata"},
        {"name":"Raccoon dog","description":"Nyctereutes procyonoides"},
        {"name":"Two-toed sloth","description":"Choloepus hoffmani"},
        {"name":"Turkey, wild","description":"Meleagris gallopavo"},
        {"name":"Stanley bustard","description":"Neotis denhami"},
        {"name":"Black-tailed prairie dog","description":"Cynomys ludovicianus"},
        {"name":"Black-footed ferret","description":"Mustela nigripes"},
        {"name":"Creeper, black-tailed tree","description":"Climacteris melanura"},
        {"name":"Hornbill, leadbeateri's ground","description":"Bucorvus leadbeateri"},
        {"name":"Tawny frogmouth","description":"Podargus strigoides"},
        {"name":"Mexican boa","description":"Boa constrictor mexicana"},
        {"name":"Southern elephant seal","description":"Mirounga leonina"},
        {"name":"Western spotted skunk","description":"Spilogale gracilis"},
        {"name":"Duck, comb","description":"Sarkidornis melanotos"},
        {"name":"Giant otter","description":"Pteronura brasiliensis"},
        {"name":"Vicuna","description":"Vicugna vicugna"},
        {"name":"Stork, greater adjutant","description":"Leptoptilus dubius"},
        {"name":"Bahama pintail","description":"Anas bahamensis"},
        {"name":"Pigeon, feral rock","description":"Columba livia"},
        {"name":"Raven, cape","description":"Corvus albicollis"},
        {"name":"Anteater, australian spiny","description":"Tachyglossus aculeatus"},
        {"name":"Phascogale, red-tailed","description":"Phascogale calura"},
        {"name":"Giraffe","description":"Giraffe camelopardalis"},
        {"name":"Tapir, brazilian","description":"Tapirus terrestris"},
        {"name":"Flycatcher, tyrant","description":"Myiarchus tuberculifer"},
        {"name":"Porcupine, north american","description":"Erethizon dorsatum"},
        {"name":"Dragon, asian water","description":"Physignathus cocincinus"},
        {"name":"Hawk, galapagos","description":"Buteo galapagoensis"},
        {"name":"Ibex","description":"Capra ibex"},
        {"name":"Porcupine, tree","description":"Coendou prehensilis"},
        {"name":"Badger, american","description":"Taxidea taxus"},
        {"name":"Western bearded dragon","description":"Amphibolurus barbatus"},
        {"name":"King vulture","description":"Sarcorhamphus papa"},
        {"name":"Goose, cereopsis","description":"Cereopsis novaehollandiae"},
        {"name":"Galapagos mockingbird","description":"Nesomimus trifasciatus"},
        {"name":"Eastern boa constrictor","description":"Acrantophis madagascariensis"},
        {"name":"Amazon parrot (unidentified)","description":"Amazona sp."},
        {"name":"North American porcupine","description":"Erethizon dorsatum"},
        {"name":"Tortoise, burmese black mountain","description":"Manouria emys"},
        {"name":"Desert tortoise","description":"Gopherus agassizii"},
        {"name":"Water moccasin","description":"Agkistrodon piscivorus"},
        {"name":"Asian lion","description":"Panthera leo persica"},
        {"name":"Black-backed magpie","description":"Gymnorhina tibicen"},
        {"name":"Elephant, african","description":"Loxodonta africana"},
        {"name":"Reedbuck, bohor","description":"Redunca redunca"},
        {"name":"Western spotted skunk","description":"Spilogale gracilis"},
        {"name":"Turtle, long-necked","description":"Chelodina longicollis"},
        {"name":"Dark-winged trumpeter","description":"Psophia viridis"},
        {"name":"Francolin, coqui","description":"Francolinus coqui"},
        {"name":"Goose, spur-winged","description":"Plectopterus gambensis"},
        {"name":"Egret, cattle","description":"Bubulcus ibis"},
        {"name":"Bee-eater, carmine","description":"Merops nubicus"},
        {"name":"Barbet, black-collared","description":"Lybius torquatus"},
        {"name":"Snake (unidentified)","description":"unavailable"},
        {"name":"Vulture, white-headed","description":"Aegypius occipitalis"},
        {"name":"Shark, blue","description":"Prionace glauca"},
        {"name":"Sulfur-crested cockatoo","description":"Cacatua galerita"},
        {"name":"Eurasian red squirrel","description":"Sciurus vulgaris"},
        {"name":"Langur, common","description":"Semnopithecus entellus"},
        {"name":"Large cormorant","description":"Phalacrocorax carbo"},
        {"name":"Shark, blue","description":"Prionace glauca"},
        {"name":"Plover, three-banded","description":"Charadrius tricollaris"},
        {"name":"Bee-eater (unidentified)","description":"Merops sp."},
        {"name":"Mongoose, yellow","description":"Cynictis penicillata"},
        {"name":"Galapagos albatross","description":"Diomedea irrorata"},
        {"name":"Little cormorant","description":"Phalacrocorax niger"},
        {"name":"Hoffman's sloth","description":"Choloepus hoffmani"},
        {"name":"Squirrel, pine","description":"Tamiasciurus hudsonicus"},
        {"name":"Nile crocodile","description":"Crocodylus niloticus"},
        {"name":"Ringtail cat","description":"Bassariscus astutus"},
        {"name":"Salmon pink bird eater tarantula","description":"Lasiodora parahybana"},
        {"name":"Stone sheep","description":"Ovis dalli stonei"},
        {"name":"Arctic tern","description":"Sterna paradisaea"},
        {"name":"Desert kangaroo rat","description":"Dipodomys deserti"},
        {"name":"Parrot, hawk-headed","description":"Deroptyus accipitrinus"},
        {"name":"Corella, long-billed","description":"Cacatua tenuirostris"},
        {"name":"White-winged dove","description":"Zenaida asiatica"},
        {"name":"Long-tailed skua","description":"Stercorarius longicausus"},
        {"name":"Wallaby, bennett's","description":"Macropus rufogriseus"},
        {"name":"Pied kingfisher","description":"Ceryle rudis"},
        {"name":"Dingo","description":"Canis dingo"},
        {"name":"Spider, wolf","description":"Lycosa godeffroyi"},
        {"name":"Egyptian goose","description":"Alopochen aegyptiacus"},
        {"name":"Tyrant flycatcher","description":"Myiarchus tuberculifer"},
        {"name":"Black-winged stilt","description":"Himantopus himantopus"},
        {"name":"Raccoon, common","description":"Procyon lotor"},
        {"name":"Grouse, greater sage","description":"Centrocercus urophasianus"}
    ]
});